### ISSUE TITLE
Clarify include path instructions in docs

### ISSUE THREAD

**Issue by philipnewcomer** [DockerBox/dockerbox#17]
Currently the docs say this:
> Add the `bin` path in the repo to your OS's include path.

The documentation should be expanded with some more info on how to do that.

**Comment by philipnewcomer** [comment]
Need clarification about ZSH. Also add note to run the Docker app after installing it.

**Comment by AaronHolbrook** [comment]
What clarification about ZSH? Anyone running ZSH should be able to manage adding a script to their PATH I think

**Comment by philipnewcomer** [comment]
Not always. Regardless, I think a wiki page for adding the path should be created which can be linked to from the main readme, then the instructions in the readme can be simplified.

**Comment by AaronHolbrook** [comment]
Makes sense
