### ISSUE TITLE
Allow php.ini max sizes to be higher

### ISSUE THREAD

**Issue by AaronHolbrook** [DockerBox/dockerbox#25]
32m might be appropriate for prod for most sites, but may be a bit low for what we're doing on dev.

I would prefer a higher default or a way to change without forking wpdocker - a custom settings file seems to be a recurring necessity here to be able to customize these types of things

![](http://d.pr/i/aebS/1PoHT7P8+)

**Comment by philipnewcomer** [comment]
@AaronHolbrook I don't see much of a downside to setting a higher default, so I think that's preferable to making this user-configurable. What is the default value that would be appropriate for your needs? 128M?

**Comment by AaronHolbrook** [comment]
I would say 128 as default, but some things we develop may need to be way higher

**Comment by philipnewcomer** [comment]
Setting a max size of 128M. If it turns out we're having to set this even higher, we can revisit the possibility of making this user-configurable.
