### ISSUE TITLE
Sync error logs to the host

### ISSUE THREAD

**Issue by philipnewcomer** [DockerBox/dockerbox#31]
We should be able to view error logs without having to open a shell in the host. Add a `log` directory in the dockerbox root where logs can be synced from the containers.

**Comment by AaronHolbrook** [comment]
Be very careful with this as a default, as VVV's log file would go unchecked and I occasionally found it to be greater than a few gigs in size.

**Comment by philipnewcomer** [comment]
I'm thinking it would make sense to clear out all logs whenever the system is started with `dockerbox up`, which should keep them from growing too excessively large. I don't think one would often need to refer back to a log from a previous session, usually you're only looking at them in real-time when you need to debug a problem.

**Comment by AaronHolbrook** [comment]
Yea exactly. Maybe to prevent increased writes to the system you could use a command to enable/disable logging? 

I.e.
`dockerbox logging enable` / `dockerbox logging disable`.

Maybe even a way for dockerbox to remember it's last setting persistent across machine boot. So if someone's turned off logging it doesn't just enable when the system is rebooted.

**Comment by philipnewcomer** [comment]
Docker has a native logging facility which might be sufficient. I've added a shortcut for viewing the logs: `dockerbox logs`

Not sure if there's a need to have an actual log file on the host or not; thoughts?

**Comment by AaronHolbrook** [comment]
At this time I would vote no; I don't feel a need to put it to a file so long as we can view it on demand.

**Comment by AaronHolbrook** [comment]
Oh - I thought running this command would allow you to tail the logs, is there a way we can add that ability to keep it running/open?

**Comment by AaronHolbrook** [comment]
Also this is all logs for everything, can we specify different things? i.e. php vs mysql for example

**Comment by philipnewcomer** [comment]
It does tail the logs, but has to run through them all first to get to the end to start tailing. Will add a restriction to the number of lines, and also allow you to pass in a container name to restrict the logs.

**Comment by AaronHolbrook** [comment]
I mean live tailing - like `tail -f`. When I run the command it spits out lines and then is done

**Comment by philipnewcomer** [comment]
@AaronHolbrook on my system it was live-tailing it, which the `-f` flag already present in the command should have been doing. Were/are you seeing something different?

**Comment by AaronHolbrook** [comment]
Huh, it's working now: ![](http://d.pr/i/ubl9/4s9yZICB+)

It wasn't staying open before - not sure why
