### ISSUE TITLE
Add dockerbox command to interface more easily with mysql

### ISSUE THREAD

**Issue by AaronHolbrook** [DockerBox/dockerbox#36]
i.e. for non-WP type sites (or if rebuilding a broken one from a docker rebuild), some commands to create a database for example would be helpful

**Comment by philipnewcomer** [comment]
You can already do direct mysql queries from the host command line, i.e.:
`dockerbox mysql "create database test;"`
`dockerbox mysql "show databases;"`

Are you thinking of something more than this?

**Comment by AaronHolbrook** [comment]
Nope that's exactly what I was looking for - should add some documentation or this to the wiki

**Comment by AaronHolbrook** [comment]
Ah, I see this at the bottom of the readme, nevermind!
