### ISSUE TITLE
Ensure new line in hosts file

### ISSUE THREAD

**Issue by morganestes** [DockerBox/dockerbox#48]
To avoid potential conflicts, please ensure there's an empty line prior to adding to the hosts file, and that each entry gets its own line.

When my first site was added to `/etc/hosts`, it was appended to the last line in the file. Since another program edited the hosts file and the line ended with `##`, it commented out the new host entry that dockerbox created.

```
## Local by Flywheel - End ##127.0.0.1 mdub.dev #dockerbox
```

should be
```
## Local by Flywheel - End ##

127.0.0.1 mdub.dev #dockerbox
```

**Comment by Jaace** [comment]
I tried to replicate this issue but was unable to.

I edited my /etc/hosts file to end in ## TESTING ## (with no newline following) and the line:
127.0.0.1 site.dev #dockerbox gets placed on a new line as expected, underneath it.

Is this issue still happening?

The place to fix would be in bin/dockerbox line 197 and I would have forked a fix. We could always just force a newline there so it adds a blank line ahead of each site, e.g.:
`NEWENTRY="\n127.0.0.1 ${DOMAIN} #dockerbox"`

**Comment by AaronHolbrook** [comment]
I like them not having a newline in between each site; maybe if you're still having problems we just have a newline before dockerbox starts adding sites?

**Comment by philipnewcomer** [comment]
@morganestes is your local copy of DockerBox up to date? The initial iteration of the hosts file handling in DockerBox wasn't as intelligent as it is now.

FWIW I'm also unable to reproduce this. I manually edited my hosts file to include only the line from your example (`## Local by Flywheel - End ##`), with no newline at the end, and after starting up DockerBox, my hosts file looks like this:
![screen shot 2017-02-08 at 7 26 19 am](https://cloud.githubusercontent.com/assets/1446874/22737245/478881f8-edd0-11e6-87e1-5118b0df72ac.png)

**Comment by morganestes** [comment]
I just updated my local repo and created a new site and can't recreate this again. Not sure what I did before, but doesn't seem to be a problem now. 🤷‍♂️
