### ISSUE TITLE
WP plugin list not a registered command

### ISSUE THREAD

**Issue by AaronHolbrook** [DockerBox/dockerbox#50]
I know this worked before, but it's no longer working:

![](http://d.pr/i/m2gR/2XKY26B1+)

Other WP commands aren't working either:

![](http://d.pr/i/PPJY/5vN4kyQI+)

This is with the latest version of DockerBox

**Comment by AaronHolbrook** [comment]
The command works now, but it's giving a warning:

`env: can't execute 'tput': No such file or directory`

![](http://d.pr/i/CMvF/rla3DcYU+)

**Comment by philipnewcomer** [comment]
The `env: can't execute 'tput': No such file or directory` warning has been occurring since the start of the project. I haven't yet taken time to trace it down, but it's not related to this issue.

I'll open a separate issue for the warning message.
